### ISSUE TITLE
adding blueprints relative to another

### ISSUE THREAD

**Issue by peendebak** [QCoDeS/broadbean#55]
Is it possible to add a Blueprint relative to another one? E.g.
```
bp1 = bb.BluePrint()  
bp1.insertSegment(0, ramp, (0, 1e-3), name='wave1', dur=3.001e-6)
bp1.insertSegmentOffset(relative='wave1', offset=1e-6, ramp, (0, 1e-3), name='wave2', dur=3.001e-6)
```

**Comment by WilliamHPNielsen** [comment]
Not currently in that form. But it is unclear to me what this is supposed to achieve. Can you elaborate? Naively I would say that since you specified the `0` for wave1, you can specify a `1` too for wave2 and get exactly the desired behaviour, but I'll bet that's not what you're after.

**Comment by eendebakpt** [comment]
If the time that `wave1` ends changes, I want the time that `wave2` starts to change with the same amount. I  can program this myself using the current broadbean capabilities, but something like relative offsets makes it easier to program and to understand.

**Comment by WilliamHPNielsen** [comment]
Sorry, I think I got something wrong from the beginning. Is the offset supposed to be in time or in signal (volts)?

**Comment by peendebak** [comment]
The offset is in time

**Comment by WilliamHPNielsen** [comment]
Hmm, then I think the answer is no and will remain no.

Let me try to clarify:
While a sequence is playing, there must always be something to output. The same clearly holds for a blueprint; a voltage must be defined for all points. Therefore, there can be no "dead time" between two segments, a segment can only start **immediately** after the previous segment. If I understand you correctly, you want to have the ability to put in a dead time between segments. But why? That time offset should be explicitly expressed in another (zero-voltaged) segment of the offset duration. By having three segments right after each other, your requirement that 
> If the time that wave1 ends changes, I want the time that wave2 starts to change with the same amount

is automatically fulfilled. That is by the way always true, since there is no dead time between segments.

**Comment by peendebak** [comment]
Ok, I see. For us no segment would mean zero voltage anyway. It works, but it means extra work for the user since we will have to add more zero-voltage segments. I think we can write some wrapper functions to make that job easier.

@lucblom @stephanlphilips

**Comment by WilliamHPNielsen** [comment]
The way waveforms are created in broadbean is indeed supposed to be rather low-level, but easy to build on. I think wrappers are the way to go.
